---
- name: Update and configure webserver-vm (Database Connection Only)
  hosts: webserver-vm
  become: yes

  vars_files:
    - "{{ playbook_dir }}/passwords.yml"

  tasks:
    - name: Ensure /var/lib/apt/lists exists
      file:
        path: /var/lib/apt/lists
        state: directory
        mode: '0755'

    - name: Ensure /var/lib/one/.one
      file:
        path: /var/lib/one/.one
        state: directory
        mode: '0755'

    - name: Create or update the oneauth file with OpenNebula credentials
      copy:
        dest: /var/lib/one/.one/one_auth
        content: |
          {{ opennebula_user }}:{{ opennebula_password }}
        mode: '0600'
        owner: root
        group: root

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        force_apt_get: yes

    - name: Install required packages for webserver and Python PostgreSQL connector
      apt:
        name: "{{ item }}"
        state: present
        force_apt_get: yes
        cache_valid_time: 3600
      loop:
        - python3-setuptools
        - python3-pip
        - apache2
        - dos2unix
        - libapache2-mod-php
        - python3-psycopg2
        - php-pgsql

    - name: Add OpenNebula GPG key
      apt_key:
        url: https://downloads.opennebula.org/repo/repo.key
        state: present

    - name: Add OpenNebula repository
      apt_repository:
        repo: "deb https://downloads.opennebula.org/repo/5.6/Ubuntu/18.04 stable opennebula"
        state: present
        filename: opennebula

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install OpenNebula tools
      apt:
        name: opennebula-tools
        state: present

    - name: Deploy website files
      copy:
        src: "{{ playbook_dir }}/../web/{{ item }}"
        dest: /var/www/html/
        mode: '0644'
      loop:
        - login.php
        - register.php
        - services.php
        - style.css
        - logout.php
        - index.php
        - vm_info.php
        - db_config.json
        - vm.py
        -
    - name: Remove default index.html
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Reformat vm.py to unix format
      command: dos2unix /var/www/html/vm.py
      notify: Restart Apache

    - name: Ensure Apache can read the oneauth file
      file:
        path: /var/lib/one/.one/one_auth
        owner: root
        group: www-data
        mode: '0640'

    - name: Allow Apache to run vm.py as root without password
      lineinfile:
        path: /etc/sudoers
        regexp: '^www-data'
        line: 'www-data ALL=(ALL) ALL'
        validate: '/usr/sbin/visudo -cf %s'
        state: present
      notify: Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted