---
- name: Configure Client VM
  hosts: client-vm
  become: yes

  vars_files:
    - "{{ playbook_dir }}/passwords.yml"

  tasks:

 #   - name: Ensure /var/lib/apt/lists exists
 #     file:
 #       path: /var/lib/apt/lists
 #       state: directory
 #       mode: '0755'

 #   - name: Ensure base packages are installed
 #     ansible.builtin.apt:
 #       name:
 #         - apt-transport-https
 #         - software-properties-common
 #       state: present
 #       update_cache: yes

 #   - name: Enable universe repository
 #     ansible.builtin.shell: |
 #       add-apt-repository universe
 #       apt-get update

 #   - name: Update apt cache
 #     ansible.builtin.apt:
 #       update_cache: yes
 #       cache_valid_time: 86400

 #   - name: Upgrade all packages
 #     ansible.builtin.apt:
 #       upgrade: dist

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 86400

    - name: Parse Public and private IPs to Client's desktop
      copy:
        src: "{{ playbook_dir }}/../misc/ips.txt"
        dest: "/home/{{ api_name_client }}/ips.txt"

